# Generated by Django 3.0.3 on 2020-03-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['id'], 'verbose_name': 'Двигатель', 'verbose_name_plural': 'Двигатели'},
        ),
    ]
