# Generated by Django 3.0.3 on 2020-03-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20200314_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_photo',
            field=models.CharField(max_length=20, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='table',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price_with_c',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена с навесом'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price_without_c',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена без навеса'),
        ),
        migrations.AlterField(
            model_name='table',
            name='volume',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='table',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Год'),
        ),
    ]
