# Generated by Django 3.0.3 on 2020-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionNone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_model_dvs', models.BooleanField(default=False, verbose_name='Модель ДВС')),
                ('is_link', models.BooleanField(default=False, verbose_name='Ссылка')),
                ('is_price_without_c', models.BooleanField(default=False, verbose_name='Цена без навеса')),
                ('is_price_with_c', models.BooleanField(default=False, verbose_name='Цена с навесом')),
                ('is_currency', models.BooleanField(default=False, verbose_name='Валюта')),
                ('is_firm', models.BooleanField(default=False, verbose_name='Фирма')),
                ('is_mark', models.BooleanField(default=False, verbose_name='Марка')),
                ('is_model', models.BooleanField(default=False, verbose_name='Модель')),
                ('is_body', models.BooleanField(default=False, verbose_name='Кузов')),
                ('is_year', models.BooleanField(default=False, verbose_name='Год')),
                ('is_drive_unit', models.BooleanField(default=False, verbose_name='Привод')),
                ('is_transmission', models.BooleanField(default=False, verbose_name='КПП')),
                ('is_volume', models.BooleanField(default=False, verbose_name='Объем')),
                ('is_horsepower', models.BooleanField(default=False, verbose_name='Количество ЛС')),
                ('is_fuel', models.BooleanField(default=False, verbose_name='Топливо')),
                ('is_name', models.BooleanField(default=False, verbose_name='Наименование')),
                ('is_information', models.BooleanField(default=False, verbose_name='Информация')),
                ('is_number_dvs', models.BooleanField(default=False, verbose_name='Номер ДВС')),
                ('is_number_oem', models.BooleanField(default=False, verbose_name='Номер ОЕМ')),
                ('is_analog', models.BooleanField(default=False, verbose_name='Аналог')),
                ('is_vin_code', models.BooleanField(default=False, verbose_name='Vin код')),
                ('is_photo', models.BooleanField(default=False, verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Права для гостей',
                'verbose_name_plural': 'Права для гостей',
            },
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'Права для групп', 'verbose_name_plural': 'Права для групп'},
        ),
    ]
