# Generated by Django 3.0.3 on 2020-03-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0005_auto_20200314_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='price_with_c',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена с навесом'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price_without_c',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Цена без навеса'),
        ),
    ]
