# Generated by Django 3.0.3 on 2020-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0007_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='is_photo',
        ),
        migrations.AddField(
            model_name='table',
            name='date_placement',
            field=models.DateField(blank=True, null=True, verbose_name='Дата размещения'),
        ),
        migrations.AddField(
            model_name='table',
            name='reliability',
            field=models.IntegerField(blank=True, null=True, verbose_name='Надежность поставки'),
        ),
    ]
