# Generated by Django 3.0.3 on 2020-03-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0010_сoefficient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='сoefficient',
            old_name='currency_rate',
            new_name='coef',
        ),
    ]
