# Generated by Django 3.0.3 on 2020-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0011_auto_20200320_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Сoefficient_guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coef', models.FloatField(verbose_name='Коофециент')),
            ],
            options={
                'verbose_name': 'Коэффициент для гостей',
                'verbose_name_plural': 'Коэффициенты для гостей',
            },
        ),
    ]
