# Generated by Django 3.0.3 on 2020-03-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('table', '0012_сoefficient_guest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTemplateGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Шаблон для гостя',
                'verbose_name_plural': 'Шаблон для гостей',
            },
        ),
        migrations.CreateModel(
            name='HomeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField(verbose_name='Шаблон')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_template', to='auth.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Шаблон для групы',
                'verbose_name_plural': 'Шаблон для групп',
            },
        ),
    ]
