# Generated by Django 3.0.3 on 2020-03-21 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('table', '0013_hometemplate_hometemplateguest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometemplate',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_template', to='auth.Group', verbose_name='Группа'),
        ),
    ]
