# Generated by Django 3.0.3 on 2020-03-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('table', '0015_auntificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_permission', to='auth.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='сoefficient',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='table_сoefficient', to='auth.Group', verbose_name='Группа'),
        ),
    ]
