# Generated by Django 3.0.3 on 2020-03-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0016_auto_20200321_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='auntificationlog',
            name='action',
            field=models.CharField(default='', max_length=300, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='auntificationlog',
            name='ip',
            field=models.CharField(max_length=20, verbose_name='IP'),
        ),
    ]
